version: '3'
services:
  app:
    container_name: app_golang
    build: .
    ports: 
      - ${API_PORT}:${API_PORT}
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - app-postgres          
    networks:
      - app_golang

  app-postgres:
    image: postgres:latest
    container_name: app_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - app_golang

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  app_golang:
    driver: bridge
